import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import { RiApps2Line } from "react-icons/ri";
import "./globals.css";
import Link from 'next/link';



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin'], // You can add 'latin-ext' or other subsets as needed
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Load all weights
  variable: '--font-inter', // Optional CSS variable
  display: 'swap', // Improves performance by using fallback fonts until the font loads
});

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistMono.variable} antialiased bg-neutral-100 dark:bg-neutral-950`}>

        <main className="max-w-screen-lg  mx-auto p-4 sm:p-4 md:p-8 lg:p-8 xl:p-8 ">
          <div className=" w-full text-gray-700 h-full grid grid-cols-1 sm:grid-cols-1 md:grid-cols-1 gap-4 lg:grid-cols-1 xl:grid-cols-1  *:rounded-2xl">
            {children}
          </div>
        </main>

        <Link href="https://course.prathambhandari.com/">

          <div className="flex items-center justify-center flex-col fixed bottom-12 right-0 -translate-x-10 w-fit rounded-full z-50 bg-primary drop-shadow-lg border-2 border-neutral-950 p-4">

            {/* <div className='text-base  font-bold text-neutral-900'>
              Start Journey
            </div> */}
            <div className='h-full w-fit'>
              <RiApps2Line className=" text-neutral-950 h-6 w-6 " />
            </div>
          </div>
        </Link>
      </body>
    </html >
  );
}
